name: Check
on: [pull_request]

jobs:
  lint:
    name: openapi lint
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-app

      - name: Lint
        run: npm run lint
