name: Deploy to S3
on:
  push:
    branches:
      - main

jobs:
  deploy-to-s3:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-app

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Copy html to S3
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: aws s3 cp dist/index.html s3://$S3_BUCKET/

      - name: Clear cache
        env:
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
